version: '3.9'

services:
  mongodb:
    image: mongo:4.4.6
    container_name: meu-mongo
    networks:
      - connect_bridge

  books: 
    image: aluradocker/alura-books:1.0
    container_name: alurabooks
    networks:
      - connect_bridge
    ports:
      - "3000:3000"  

networks:
  connect_bridge:
    driver: bridge
